package hust.thread.Synchronized.method;

/**
 * 当一个线程执行的代码出现异常时，其所持有的锁会自动释放。
 * 
 * 测试（略）：两个线程，线程1持有对象锁3秒后抛出异常，线程2才可操作该对象的Synchronized方法。
 * 
 * @author 2016-01-05
 *
 */
public class SynchronizedException {

}
